-- MySQL Script generated by MySQL Workbench
-- Wed Oct 29 19:25:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cornershop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cornershop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cornershop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cornershop` ;

-- -----------------------------------------------------
-- Table `cornershop`.`coustomers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cornershop`.`coustomers` (
  `Customer_ID` INT NOT NULL,
  `Customer_FirstName` VARCHAR(45) NOT NULL,
  `Customer_LastName` VARCHAR(45) NOT NULL,
  `Customer_Email` VARCHAR(45) NOT NULL,
  `Customer_Address` VARCHAR(45) NOT NULL,
  `Customer_Phone` VARCHAR(45) NOT NULL,
  `Customer_Points` VARCHAR(45) NOT NULL,
  `Customer_JoinDate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cornershop`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cornershop`.`employees` (
  `Employee_ID` INT NOT NULL,
  `Employee_FirstName` VARCHAR(45) NOT NULL,
  `Employee_LastName` VARCHAR(45) NOT NULL,
  `Employee_DateBirth` DATE NOT NULL,
  `Employee_Position` ENUM('Manager', 'Cashier', 'Cleaner', 'Supervisor') NOT NULL,
  `Employee_Address` VARCHAR(45) NOT NULL,
  `Employee_Phone` VARCHAR(45) NOT NULL,
  `Employee_StartDate` DATE NOT NULL,
  `Employee_EndDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Employee_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cornershop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cornershop`.`orders` (
  `Order_ID` INT NOT NULL,
  `Order_Date` DATE NOT NULL,
  `Customer_ID` INT NOT NULL,
  `Employee_ID` INT NOT NULL,
  PRIMARY KEY (`Order_ID`),
  INDEX `Customer_ID_idx` (`Customer_ID` ASC) VISIBLE,
  INDEX `Employee_ID_idx` (`Employee_ID` ASC) VISIBLE,
  CONSTRAINT `Customer_ID`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `cornershop`.`coustomers` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Employee_ID`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `cornershop`.`employees` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cornershop`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cornershop`.`order_details` (
  `Orderdetails_ID` INT NOT NULL,
  `Product_ID` VARCHAR(45) NOT NULL,
  `Order_Id` INT NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`Orderdetails_ID`),
  INDEX `Order_ID_idx` (`Order_Id` ASC) VISIBLE,
  CONSTRAINT `Order_ID`
    FOREIGN KEY (`Order_Id`)
    REFERENCES `cornershop`.`orders` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cornershop`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cornershop`.`suppliers` (
  `Supplier_ID` INT NOT NULL,
  `Supplier_Name` VARCHAR(45) NOT NULL,
  `Supplier_Address` VARCHAR(45) NOT NULL,
  `Supplier_ContactPerson` VARCHAR(45) NOT NULL,
  `Supplier_City` VARCHAR(45) NOT NULL,
  `Supplier_Country` VARCHAR(45) NOT NULL,
  `Supplier_Phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Supplier_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cornershop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cornershop`.`products` (
  `Product_ID` INT NOT NULL,
  `Product_Name` VARCHAR(45) NOT NULL,
  `Product_SalePrice` INT NOT NULL,
  `Product_Quantity` INT NOT NULL,
  `Product_BuyingPrice` INT NOT NULL,
  `Supplier_ID` INT NOT NULL,
  PRIMARY KEY (`Product_ID`),
  INDEX `Supplier_ID_idx` (`Supplier_ID` ASC) VISIBLE,
  CONSTRAINT `Supplier_ID`
    FOREIGN KEY (`Supplier_ID`)
    REFERENCES `cornershop`.`suppliers` (`Supplier_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
